# Generated by Django 4.1 on 2023-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
